apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: deploy1
spec:	
    replicas: 3
    template: 
      metadata:
        labels:
           app: app-v1
      spec:
       containers:
       - name: sample-ctr
         image: samiralur/newdisplayerv_1:v2
         ports:
         - containerPort: 80
