apiVersion: v1
kind: Service
metadata:
   name: svc1
   labels:
      app: app-v1
spec:
  ports:
  - port: 3000
    targetPort: 32000
    protocol: TCP
  selector:
     app: app-v1
  type: LoadBalancer
